/**
 * Operations Menu Manager
 * Provides a quick-access menu for common Figma design operations
 * Each operation is a pre-formatted prompt ready to copy to Claude
 */

class OperationsMenu {
  constructor() {
    /* OPERATION_PROMPTS:START — generated by scripts/build-operation-prompts.js; do not edit by hand */
    const OPERATION_PROMPTS = [
      {
        "id": "convert_to_grid",
        "category": "Layout",
        "title": "Convert to Grid",
        "description": "Convert to Figma Grid with minimal layers",
        "triggers": [
          "convert to grid",
          "gridify",
          "grid layout",
          "fewer layers"
        ],
        "icon": "📊",
        "prompt": "Convert to Grid - rebuild the selection as a Figma Grid that renders identically with the fewest layers.\n\nSetup: join_channel -> check_figma_connection -> get_selection. Nothing selected: ask which frame, then stop. Work only inside that selection; report problems elsewhere instead of fixing them.\n\nLoad figma_skill \"Grid_Convert_v1\" and follow it; this prompt only sets scope and limits.\nRead geometry with get_nodes_info, plan via convert_layout mode \"grid\", show me the plan (tracks, spans, which wrappers go) and wait for approval before applying.\nIdentical render beats fewer layers: where a Grid cannot reproduce the render exactly, keep Auto Layout or leave it and say so. Never nudge a layer to make a Grid fit.\nKeep gap and padding bound to their variables. Remove wrappers only through clean_layers, and only ones a Grid cell makes redundant.\n\nNever: move or resize an absolute-positioned layer - change size or layout without checking clipsContent - detach instances - break masks, variants, component properties or prototype links - alter copy, colour, type or imagery unasked - invent a token, style or component name.\n\nVerify: export_node_as_image before and after - it must look identical unless this task asked otherwise; re-read changed nodes with get_nodes_info and undo anything that moved, clipped or overlapped by accident.\nReport: per change, node ID and before -> after; what you skipped and why; what you need from me. Never report a step no tool result confirmed."
      },
      {
        "id": "rename_layers",
        "category": "Organization",
        "title": "Rename Layers",
        "description": "Semantic naming conventions (BEM-like)",
        "triggers": [
          "rename layers",
          "clean up layers",
          "naming conventions",
          "developer handoff"
        ],
        "icon": "📝",
        "prompt": "Rename Layers - give every layer the name a senior frontend developer would write.\n\nSetup: join_channel -> check_figma_connection -> get_selection. Nothing selected: ask which frame, then stop. Work only inside that selection; report problems elsewhere instead of fixing them.\n\nLoad figma_skill \"Layer_Rename_v1\" and use its convention; do not invent one.\nRead get_nodes_info and export_node_as_image first, so each name says what the layer is on screen: header, hero, card, card__title, button--primary. Nothing stays \"Frame 24\", \"Group 5\" or \"Copy 3\".\nApply with rename_node batched through figma_batch - the whole selection in one pass, no mid-way questions about which convention I prefer.\nNames only: no spacing, typography, colour, sizing, structure or responsive work. Do not rename component properties, variants or variables (it breaks bindings); skip locked layers and instance internals.\n\nNever: move or resize an absolute-positioned layer - change size or layout without checking clipsContent - detach instances - break masks, variants, component properties or prototype links - alter copy, colour, type or imagery unasked - invent a token, style or component name.\n\nVerify: export_node_as_image before and after - it must look identical unless this task asked otherwise; re-read changed nodes with get_nodes_info and undo anything that moved, clipped or overlapped by accident.\nReport: per change, node ID and before -> after; what you skipped and why; what you need from me. Never report a step no tool result confirmed."
      },
      {
        "id": "make_responsive",
        "category": "Responsive",
        "title": "Make Responsive",
        "description": "Adapt for tablet (768px) and mobile (320px)",
        "triggers": [
          "make responsive",
          "responsive",
          "tablet",
          "mobile"
        ],
        "icon": "📱",
        "prompt": "Make Responsive - adapt the selection to one breakpoint, on a duplicate, without redesigning it.\n\nSetup: join_channel -> check_figma_connection -> get_selection. Nothing selected: ask which frame, then stop. Work only inside that selection; report problems elsewhere instead of fixing them.\n\nLoad figma_skill \"Responsive_Apply_v1\".\nAsk which breakpoint - Tablet 768 or Mobile 320 - and stop until I answer. One per run. clone_node the frame and work on the duplicate; leave the original alone.\nEvery value comes from the file: get_variables -> find_variable -> switch_variable_mode for this breakpoint -> apply_variable_to_node. No token for it? Ask; never create one.\nSizing: containers, cards, text blocks and columns Fill width + Hug height (set_layout_sizing); buttons hug both. No fixed height on content, ever. Text wraps and grows - never shrink a font, change a style or clip text to fit.\nanalyze_responsive before, validate_responsive after. Finish this breakpoint, report, stop - do not start the other one.\n\nNever: move or resize an absolute-positioned layer - change size or layout without checking clipsContent - detach instances - break masks, variants, component properties or prototype links - alter copy, colour, type or imagery unasked - invent a token, style or component name.\n\nVerify: export_node_as_image before and after - it must look identical unless this task asked otherwise; re-read changed nodes with get_nodes_info and undo anything that moved, clipped or overlapped by accident.\nReport: per change, node ID and before -> after; what you skipped and why; what you need from me. Never report a step no tool result confirmed."
      },
      {
        "id": "optimize_layers",
        "category": "Organization",
        "title": "Optimize Layers",
        "description": "Remove wrappers and flatten structure",
        "triggers": [
          "optimize layers",
          "fewer layers",
          "clean up",
          "flatten"
        ],
        "icon": "✨",
        "prompt": "Optimize Layers - flatten the structure to the smallest tree that renders identically.\n\nSetup: join_channel -> check_figma_connection -> get_selection. Nothing selected: ask which frame, then stop. Work only inside that selection; report problems elsewhere instead of fixing them.\n\nScan the whole selection with get_nodes_info, list what you would remove or merge and why, and wait for approval before deleting anything.\nRemove through clean_layers: empty frames and groups, single-child wrappers that do nothing, accidental duplicates, Auto Layout frames with no layout job. Collapse to one level of Auto Layout where one frame does the work.\nFor repeating rows or cards, propose convert_layout mode \"grid\" - but only if spacing, alignment and wrapping stay identical; otherwise keep the structure and say why.\nKeep: components, properties, variants, masks, prototype layers, and every bound padding/gap token (check get_node_variable_bindings before and after).\nStructure only - no redesign, typography, colour, content or spacing changes. The result must be pixel-identical.\n\nNever: move or resize an absolute-positioned layer - change size or layout without checking clipsContent - detach instances - break masks, variants, component properties or prototype links - alter copy, colour, type or imagery unasked - invent a token, style or component name.\n\nVerify: export_node_as_image before and after - it must look identical unless this task asked otherwise; re-read changed nodes with get_nodes_info and undo anything that moved, clipped or overlapped by accident.\nReport: per change, node ID and before -> after; what you skipped and why; what you need from me. Never report a step no tool result confirmed."
      },
      {
        "id": "design_system",
        "category": "Design System",
        "title": "Design System First",
        "description": "Reuse existing components & variables",
        "triggers": [
          "design system",
          "reuse",
          "components",
          "variables"
        ],
        "icon": "🎨",
        "prompt": "Design System First - inventory what the file already has and reuse it instead of creating anything.\n\nSetup: join_channel -> check_figma_connection -> get_selection. Nothing selected: ask which frame, then stop. Work only inside that selection; report problems elsewhere instead of fixing them.\n\nInventory: get_design_system, get_variables, get_styles, get_local_components, get_remote_components. Report the collections, modes, styles and components that exist.\nMap the selection with get_node_variable_bindings and match_design_tokens. Table: node ID, property, current raw value, the existing variable or style that matches, or \"no match\".\nShow the table and wait. Bind only the rows I approve - apply_variable_to_node, apply_variable_bindings, set_text_style_id, set_instance_variant.\nExact matches only: a near value gets reported, never snapped. Never create a variable, style or component to close a gap, and never replace a bound token with a raw value.\n\nNever: move or resize an absolute-positioned layer - change size or layout without checking clipsContent - detach instances - break masks, variants, component properties or prototype links - alter copy, colour, type or imagery unasked - invent a token, style or component name.\n\nVerify: export_node_as_image before and after - it must look identical unless this task asked otherwise; re-read changed nodes with get_nodes_info and undo anything that moved, clipped or overlapped by accident.\nReport: per change, node ID and before -> after; what you skipped and why; what you need from me. Never report a step no tool result confirmed."
      },
      {
        "id": "fix_typography",
        "category": "Typography",
        "title": "Fix Typography",
        "description": "Bind to text styles and ensure hierarchy",
        "triggers": [
          "fix typography",
          "text styles",
          "font consistency",
          "hierarchy"
        ],
        "icon": "🔤",
        "prompt": "Fix Typography - bind text to the file's existing text styles and make the hierarchy consistent.\n\nSetup: join_channel -> check_figma_connection -> get_selection. Nothing selected: ask which frame, then stop. Work only inside that selection; report problems elsewhere instead of fixing them.\n\nRead get_styles for the styles and scan_text_nodes for the text; call get_styled_text_segments before touching anything with mixed formatting, so per-segment styling is not flattened.\nTable: text layer, node ID, current font/size/weight/line-height, and the text style whose values match exactly. Show it, wait, then bind approved rows with set_text_style_id.\nA near match is not a match - list it as unmatched and ask. Never resize text to make a style fit, and never create a style.\nText is Auto Height (fix_text_sizing / set_layout_sizing), never a fixed box. Never shrink type, tighten line height or cut copy to solve overflow - fix the container or report it. Do not change wording.\nFlag inconsistent hierarchy - heading levels, repeated card titles, body copy - before changing it.\n\nNever: move or resize an absolute-positioned layer - change size or layout without checking clipsContent - detach instances - break masks, variants, component properties or prototype links - alter copy, colour, type or imagery unasked - invent a token, style or component name.\n\nVerify: export_node_as_image before and after - it must look identical unless this task asked otherwise; re-read changed nodes with get_nodes_info and undo anything that moved, clipped or overlapped by accident.\nReport: per change, node ID and before -> after; what you skipped and why; what you need from me. Never report a step no tool result confirmed."
      },
      {
        "id": "audit_spacing",
        "category": "Layout",
        "title": "Audit Spacing",
        "description": "Standardize padding & gaps with tokens",
        "triggers": [
          "audit spacing",
          "spacing review",
          "padding",
          "gaps"
        ],
        "icon": "📐",
        "prompt": "Audit Spacing - report every padding and gap, then bind the approved ones to existing tokens.\n\nSetup: join_channel -> check_figma_connection -> get_selection. Nothing selected: ask which frame, then stop. Work only inside that selection; report problems elsewhere instead of fixing them.\n\nAudit first, change nothing: get_variables and get_design_system for the tokens, get_nodes_info and get_node_variable_bindings for current values, then match_design_tokens.\nReport per layer: node ID, property (padding sides, item spacing, counter-axis spacing), value, bound or raw, matching token. Group as: already bound / exact token available / no token / inconsistent with a sibling.\nAfter approval, bind with apply_variable_to_node or apply_variable_bindings and set unbindable values through set_auto_layout.\nExact matches only - never round to a \"close\" token and never create one; say which value needs a token and ask.\nSpacing only: no resizing, restructuring or typography. A changed gap changes every ancestor's height, so re-check the frame afterwards.\n\nNever: move or resize an absolute-positioned layer - change size or layout without checking clipsContent - detach instances - break masks, variants, component properties or prototype links - alter copy, colour, type or imagery unasked - invent a token, style or component name.\n\nVerify: export_node_as_image before and after - it must look identical unless this task asked otherwise; re-read changed nodes with get_nodes_info and undo anything that moved, clipped or overlapped by accident.\nReport: per change, node ID and before -> after; what you skipped and why; what you need from me. Never report a step no tool result confirmed."
      },
      {
        "id": "hug_heights",
        "category": "Responsive",
        "title": "Apply Hug Heights",
        "description": "Replace fixed heights with Hug Contents",
        "triggers": [
          "hug height",
          "hug contents",
          "fixed height",
          "auto height"
        ],
        "icon": "📏",
        "prompt": "Apply Hug Heights - replace fixed heights on content layers with Hug Contents so the design grows with its content.\n\nSetup: join_channel -> check_figma_connection -> get_selection. Nothing selected: ask which frame, then stop. Work only inside that selection; report problems elsewhere instead of fixing them.\n\nList every fixed height (get_nodes_info) with node ID, value and content, each marked \"should hug\" or \"deliberately fixed\". Show the list before changing anything.\nHug: sections, wrappers, text and heading containers, cards, hero, CTA, form, nav and footer blocks - any frame whose height follows its children. Apply set_layout_sizing vertical HUG; it needs Auto Layout, so ask before adding one. Text goes to Auto Height via fix_text_sizing.\nKeep fixed: icons, avatars, small controls, deliberate image crops, brand assets, components with an intentional spec. Unsure whether a height is deliberate? Ask.\nHeights shift as parents start hugging: walk up the tree and confirm nothing is clipped, overlapping or collapsed to zero. Never re-fix a height or shrink text to solve overflow. Finish with validate_responsive.\n\nNever: move or resize an absolute-positioned layer - change size or layout without checking clipsContent - detach instances - break masks, variants, component properties or prototype links - alter copy, colour, type or imagery unasked - invent a token, style or component name.\n\nVerify: export_node_as_image before and after - it must look identical unless this task asked otherwise; re-read changed nodes with get_nodes_info and undo anything that moved, clipped or overlapped by accident.\nReport: per change, node ID and before -> after; what you skipped and why; what you need from me. Never report a step no tool result confirmed."
      }
    ];
    /* OPERATION_PROMPTS:END */

    this.operations = OPERATION_PROMPTS.map(op => ({ ...op }));

    this.filteredOperations = [...this.operations];
    this.searchQuery = '';
    this.selectedCategory = 'all';
  }

  /**
   * Get all available categories
   */
  getCategories() {
    const categories = new Set(this.operations.map(op => op.category));
    return ['all', ...Array.from(categories).sort()];
  }

  /**
   * Search and filter operations
   */
  search(query) {
    this.searchQuery = query.toLowerCase();
    this.filterOperations();
  }

  /**
   * Filter by category
   */
  setCategory(category) {
    this.selectedCategory = category;
    this.filterOperations();
  }

  /**
   * Apply current filters
   */
  filterOperations() {
    this.filteredOperations = this.operations.filter(op => {
      const matchesSearch =
        !this.searchQuery ||
        op.title.toLowerCase().includes(this.searchQuery) ||
        op.description.toLowerCase().includes(this.searchQuery) ||
        op.triggers.some(t => t.includes(this.searchQuery));

      const matchesCategory =
        this.selectedCategory === 'all' || op.category === this.selectedCategory;

      return matchesSearch && matchesCategory;
    });
  }

  /**
   * Get formatted prompt for operation
   */
  getPrompt(operationId) {
    const op = this.operations.find(o => o.id === operationId);
    if (!op) return '';

    // Format as a clean, ready-to-use prompt for Claude
    return `${op.prompt}`;
  }

  /**
   * Get all operations
   */
  getAll() {
    return this.filteredOperations;
  }
}

// Export for use in the plugin UI
if (typeof module !== 'undefined' && module.exports) {
  module.exports = OperationsMenu;
}
